-- 코드를 입력하세요
select P.PRODUCT_CODE, SUM(O.SALES_AMOUNT)*P.PRICE as SALES     
FROM PRODUCT P inner join OFFLINE_SALE O on P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY p.PRODUCT_ID
ORDER BY SALES DESC, p.PRODUCT_CODE ASC